# Action that performs various checks on deployment
---
  name: Checks
  on: [push]
  
  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04 # runner
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Checkout repository
          uses: actions/checkout@v4   
  
        - name: Run Tests
          run: docker-compose run --rm app sh -c "python manage.py test"
  
        - name: Run Lint Checks
          run: docker-compose run --rm app sh -c "flake8"
  