# action that perform various checks on deployement
---
name : Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-28.04 #runner 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrects.DOCKERHUB_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"   
      - name: Lint 
        run: docker compose run --rm app sh -c "flake8"        